// Decompiled with JetBrains decompiler
// Type: AMS.Form_ReservationDMS
// Assembly: AMS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 99EBC956-E2B8-4955-9E76-E3E000435543
// Assembly location: C:\Users\Administrator\Desktop\birchridge\AMS 2017\AMS.exe

using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

#nullable disable
namespace AMS
{
  public class Form_ReservationDMS : Form
  {
    private IContainer components;
    public ToolTip ToolTip1;
    public TextBox txtNoOfDays;
    public TextBox txtFirstName;
    public TextBox txtDeposit;
    public TextBox txtSurName;
    public TextBox txtClientID;
    public TextBox txtReservationRef;
    public MaskedTextBox mskBookingStart;
    public MaskedTextBox mskBookingEnd;
    public MaskedTextBox mskEndDate;
    public Button cmdReturn;
    public MaskedTextBox mskStartDate;
    public Button cmdView;
    public ComboBox cboRoomType;
    public Button cmdConfirm;
    public ComboBox cboBuilding;
    public Button cmdNewReserve;
    public Button cmdReservedView;
    public Button cmdPrint;
    public Button cmdClear;
    public GroupBox UnitFrame;
    public Label _lblBURoom_4;
    public Label _lblBURoom_3;
    public Label _lblBURoom_2;
    public Label _lblBURoom_1;
    public Label _lblBURoom_0;
    public Button cmdExisting;
    public MaskedTextBox MaskEdBox2;
    public MaskedTextBox MaskEdBox4;
    public Label lblRType;
    public Label lblOldDepositAmount;
    public Label lblOldDeposit;
    public Label lblDifference;
    public Label lblDiffAmount;
    public Label lblOldRoomNo;
    public Label lblOldRoom;
    public Label Label12;
    public Label lblOldRoomType;
    public Label Label13;
    public Label lblBookingRoomNo;
    public Label Label11;
    public Label Label9;
    public Label Label2;
    public GroupBox ReservationFrame;
    public Label Label1;
    public Label Label7;
    public Label Label21;
    public Label Label5;
    public Label Label3;
    public Label Label6;
    public TextBox txtRoomType;
    public Label lblBuildingType;
    public Label lblMessage;
    public Label lbBuilding;
    public Label Label8;
    public Label Label17;
    public Label Label18;

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.components = (IContainer) new System.ComponentModel.Container();
      ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (Form_ReservationDMS));
      this.ToolTip1 = new ToolTip(this.components);
      this.txtNoOfDays = new TextBox();
      this.txtFirstName = new TextBox();
      this.txtDeposit = new TextBox();
      this.txtSurName = new TextBox();
      this.txtClientID = new TextBox();
      this.txtReservationRef = new TextBox();
      this.mskBookingStart = new MaskedTextBox();
      this.mskBookingEnd = new MaskedTextBox();
      this.mskEndDate = new MaskedTextBox();
      this.cmdReturn = new Button();
      this.mskStartDate = new MaskedTextBox();
      this.cmdView = new Button();
      this.cboRoomType = new ComboBox();
      this.cmdConfirm = new Button();
      this.cboBuilding = new ComboBox();
      this.cmdNewReserve = new Button();
      this.cmdReservedView = new Button();
      this.cmdPrint = new Button();
      this.cmdClear = new Button();
      this.UnitFrame = new GroupBox();
      this._lblBURoom_4 = new Label();
      this._lblBURoom_3 = new Label();
      this._lblBURoom_2 = new Label();
      this._lblBURoom_1 = new Label();
      this._lblBURoom_0 = new Label();
      this.cmdExisting = new Button();
      this.MaskEdBox2 = new MaskedTextBox();
      this.MaskEdBox4 = new MaskedTextBox();
      this.lblRType = new Label();
      this.lblOldDepositAmount = new Label();
      this.lblOldDeposit = new Label();
      this.lblDifference = new Label();
      this.lblDiffAmount = new Label();
      this.lblOldRoomNo = new Label();
      this.lblOldRoom = new Label();
      this.Label12 = new Label();
      this.lblOldRoomType = new Label();
      this.Label13 = new Label();
      this.lblBookingRoomNo = new Label();
      this.Label11 = new Label();
      this.Label9 = new Label();
      this.Label2 = new Label();
      this.ReservationFrame = new GroupBox();
      this.Label1 = new Label();
      this.Label7 = new Label();
      this.Label21 = new Label();
      this.Label5 = new Label();
      this.Label3 = new Label();
      this.Label6 = new Label();
      this.txtRoomType = new TextBox();
      this.lblBuildingType = new Label();
      this.lblMessage = new Label();
      this.lbBuilding = new Label();
      this.Label8 = new Label();
      this.Label17 = new Label();
      this.Label18 = new Label();
      this.UnitFrame.SuspendLayout();
      this.ReservationFrame.SuspendLayout();
      this.SuspendLayout();
      this.txtNoOfDays.AcceptsReturn = true;
      this.txtNoOfDays.BackColor = SystemColors.Window;
      this.txtNoOfDays.Cursor = Cursors.IBeam;
      this.txtNoOfDays.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtNoOfDays.ForeColor = SystemColors.WindowText;
      this.txtNoOfDays.Location = new Point(104, 312);
      this.txtNoOfDays.MaxLength = 0;
      this.txtNoOfDays.Name = "txtNoOfDays";
      this.txtNoOfDays.ReadOnly = true;
      this.txtNoOfDays.RightToLeft = RightToLeft.No;
      this.txtNoOfDays.Size = new Size(49, 20);
      this.txtNoOfDays.TabIndex = 5;
      this.txtNoOfDays.TextAlign = HorizontalAlignment.Center;
      this.ToolTip1.SetToolTip((Control) this.txtNoOfDays, "Booking Duration");
      this.txtFirstName.AcceptsReturn = true;
      this.txtFirstName.BackColor = SystemColors.Window;
      this.txtFirstName.Cursor = Cursors.IBeam;
      this.txtFirstName.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtFirstName.ForeColor = SystemColors.WindowText;
      this.txtFirstName.Location = new Point(16, 104);
      this.txtFirstName.MaxLength = 0;
      this.txtFirstName.Name = "txtFirstName";
      this.txtFirstName.RightToLeft = RightToLeft.No;
      this.txtFirstName.Size = new Size(177, 20);
      this.txtFirstName.TabIndex = 1;
      this.txtFirstName.TextAlign = HorizontalAlignment.Center;
      this.ToolTip1.SetToolTip((Control) this.txtFirstName, "Enter First Name");
      this.txtDeposit.AcceptsReturn = true;
      this.txtDeposit.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.txtDeposit.Cursor = Cursors.IBeam;
      this.txtDeposit.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtDeposit.ForeColor = Color.Black;
      this.txtDeposit.Location = new Point(72, 344);
      this.txtDeposit.MaxLength = 0;
      this.txtDeposit.Name = "txtDeposit";
      this.txtDeposit.RightToLeft = RightToLeft.No;
      this.txtDeposit.Size = new Size(65, 22);
      this.txtDeposit.TabIndex = 6;
      this.txtDeposit.TextAlign = HorizontalAlignment.Center;
      this.ToolTip1.SetToolTip((Control) this.txtDeposit, "Enter Deposit Amount");
      this.txtSurName.AcceptsReturn = true;
      this.txtSurName.BackColor = SystemColors.Window;
      this.txtSurName.Cursor = Cursors.IBeam;
      this.txtSurName.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtSurName.ForeColor = SystemColors.WindowText;
      this.txtSurName.Location = new Point(16, 144);
      this.txtSurName.MaxLength = 0;
      this.txtSurName.Name = "txtSurName";
      this.txtSurName.RightToLeft = RightToLeft.No;
      this.txtSurName.Size = new Size(177, 20);
      this.txtSurName.TabIndex = 2;
      this.txtSurName.TextAlign = HorizontalAlignment.Center;
      this.ToolTip1.SetToolTip((Control) this.txtSurName, "Enter SurName");
      this.txtClientID.AcceptsReturn = true;
      this.txtClientID.BackColor = SystemColors.Window;
      this.txtClientID.Cursor = Cursors.IBeam;
      this.txtClientID.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtClientID.ForeColor = Color.Red;
      this.txtClientID.Location = new Point(64, 64);
      this.txtClientID.MaxLength = 8;
      this.txtClientID.Name = "txtClientID";
      this.txtClientID.RightToLeft = RightToLeft.No;
      this.txtClientID.Size = new Size(81, 20);
      this.txtClientID.TabIndex = 0;
      this.txtClientID.TextAlign = HorizontalAlignment.Center;
      this.ToolTip1.SetToolTip((Control) this.txtClientID, "Enter Guest ID");
      this.txtReservationRef.AcceptsReturn = true;
      this.txtReservationRef.BackColor = SystemColors.Window;
      this.txtReservationRef.Cursor = Cursors.IBeam;
      this.txtReservationRef.Font = new Font("Arial", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtReservationRef.ForeColor = Color.Red;
      this.txtReservationRef.Location = new Point(48, 32);
      this.txtReservationRef.MaxLength = 10;
      this.txtReservationRef.Name = "txtReservationRef";
      this.txtReservationRef.RightToLeft = RightToLeft.No;
      this.txtReservationRef.Size = new Size(105, 26);
      this.txtReservationRef.TabIndex = 24;
      this.txtReservationRef.TextAlign = HorizontalAlignment.Center;
      this.ToolTip1.SetToolTip((Control) this.txtReservationRef, "Reservation Reference No.");
      this.mskBookingStart.AllowPromptAsInput = false;
      this.mskBookingStart.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.mskBookingStart.ForeColor = Color.Blue;
      this.mskBookingStart.Location = new Point(104, 256);
      this.mskBookingStart.Mask = "####-##-##";
      this.mskBookingStart.Name = "mskBookingStart";
      this.mskBookingStart.Size = new Size(81, 20);
      this.mskBookingStart.TabIndex = 3;
      this.ToolTip1.SetToolTip((Control) this.mskBookingStart, "Enter Booking Start Date");
      this.mskBookingEnd.AllowPromptAsInput = false;
      this.mskBookingEnd.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.mskBookingEnd.ForeColor = Color.Blue;
      this.mskBookingEnd.Location = new Point(104, 288);
      this.mskBookingEnd.Mask = "####-##-##";
      this.mskBookingEnd.Name = "mskBookingEnd";
      this.mskBookingEnd.Size = new Size(81, 20);
      this.mskBookingEnd.TabIndex = 4;
      this.ToolTip1.SetToolTip((Control) this.mskBookingEnd, "Enter Booking End Date");
      this.mskEndDate.AllowPromptAsInput = false;
      this.mskEndDate.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.mskEndDate.ForeColor = Color.Blue;
      this.mskEndDate.Location = new Point(372, 25);
      this.mskEndDate.Mask = "####-##-##";
      this.mskEndDate.Name = "mskEndDate";
      this.mskEndDate.Size = new Size(81, 20);
      this.mskEndDate.TabIndex = 477;
      this.ToolTip1.SetToolTip((Control) this.mskEndDate, "Enter End Date");
      this.cmdReturn.BackColor = Color.FromArgb(0, 192, 192);
      this.cmdReturn.Cursor = Cursors.Default;
      this.cmdReturn.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.cmdReturn.ForeColor = SystemColors.ControlText;
      this.cmdReturn.Image = (Image) componentResourceManager.GetObject("cmdReturn.Image");
      this.cmdReturn.Location = new Point(748, 465);
      this.cmdReturn.Name = "cmdReturn";
      this.cmdReturn.RightToLeft = RightToLeft.No;
      this.cmdReturn.Size = new Size(49, 55);
      this.cmdReturn.TabIndex = 473;
      this.cmdReturn.Text = "Retur&n";
      this.cmdReturn.TextAlign = ContentAlignment.BottomCenter;
      this.ToolTip1.SetToolTip((Control) this.cmdReturn, "Return to Operation Screen");
      this.cmdReturn.UseVisualStyleBackColor = false;
      this.cmdReturn.Click += new EventHandler(this.cmdReturn_Click);
      this.mskStartDate.AllowPromptAsInput = false;
      this.mskStartDate.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.mskStartDate.ForeColor = Color.Blue;
      this.mskStartDate.Location = new Point(156, 25);
      this.mskStartDate.Mask = "####-##-##";
      this.mskStartDate.Name = "mskStartDate";
      this.mskStartDate.Size = new Size(81, 20);
      this.mskStartDate.TabIndex = 476;
      this.ToolTip1.SetToolTip((Control) this.mskStartDate, "Enter Start Date");
      this.cmdView.BackColor = Color.FromArgb(192, 192, 192);
      this.cmdView.Cursor = Cursors.Default;
      this.cmdView.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.cmdView.ForeColor = SystemColors.ControlText;
      this.cmdView.Image = (Image) componentResourceManager.GetObject("cmdView.Image");
      this.cmdView.Location = new Point(484, 1);
      this.cmdView.Name = "cmdView";
      this.cmdView.RightToLeft = RightToLeft.No;
      this.cmdView.Size = new Size(97, 47);
      this.cmdView.TabIndex = 478;
      this.cmdView.Text = "&View Room";
      this.cmdView.TextAlign = ContentAlignment.BottomCenter;
      this.ToolTip1.SetToolTip((Control) this.cmdView, "Click to View Rooms");
      this.cmdView.UseVisualStyleBackColor = false;
      this.cmdView.Click += new EventHandler(this.cmdView_Click);
      this.cboRoomType.BackColor = SystemColors.Window;
      this.cboRoomType.Cursor = Cursors.Default;
      this.cboRoomType.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.cboRoomType.ForeColor = SystemColors.WindowText;
      this.cboRoomType.Location = new Point(372, 1);
      this.cboRoomType.Name = "cboRoomType";
      this.cboRoomType.RightToLeft = RightToLeft.No;
      this.cboRoomType.Size = new Size(81, 22);
      this.cboRoomType.TabIndex = 475;
      this.ToolTip1.SetToolTip((Control) this.cboRoomType, "Choose Room Type");
      this.cmdConfirm.BackColor = Color.FromArgb((int) byte.MaxValue, 192, 192);
      this.cmdConfirm.Cursor = Cursors.Default;
      this.cmdConfirm.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.cmdConfirm.ForeColor = SystemColors.ControlText;
      this.cmdConfirm.Image = (Image) componentResourceManager.GetObject("cmdConfirm.Image");
      this.cmdConfirm.Location = new Point(588, 465);
      this.cmdConfirm.Name = "cmdConfirm";
      this.cmdConfirm.RightToLeft = RightToLeft.No;
      this.cmdConfirm.Size = new Size(49, 55);
      this.cmdConfirm.TabIndex = 470;
      this.cmdConfirm.Text = "Con&firm";
      this.cmdConfirm.TextAlign = ContentAlignment.BottomCenter;
      this.ToolTip1.SetToolTip((Control) this.cmdConfirm, "Click to Confirm & Update");
      this.cmdConfirm.UseVisualStyleBackColor = false;
      this.cmdConfirm.Click += new EventHandler(this.cmdConfirm_Click);
      this.cboBuilding.BackColor = SystemColors.Window;
      this.cboBuilding.Cursor = Cursors.Default;
      this.cboBuilding.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.cboBuilding.ForeColor = SystemColors.WindowText;
      this.cboBuilding.Location = new Point(156, 1);
      this.cboBuilding.Name = "cboBuilding";
      this.cboBuilding.RightToLeft = RightToLeft.No;
      this.cboBuilding.Size = new Size(49, 22);
      this.cboBuilding.TabIndex = 474;
      this.ToolTip1.SetToolTip((Control) this.cboBuilding, "Choose Building No.");
      this.cmdNewReserve.BackColor = Color.FromArgb(128, (int) byte.MaxValue, 128);
      this.cmdNewReserve.Cursor = Cursors.Default;
      this.cmdNewReserve.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.cmdNewReserve.ForeColor = SystemColors.ControlText;
      this.cmdNewReserve.Location = new Point(588, 9);
      this.cmdNewReserve.Name = "cmdNewReserve";
      this.cmdNewReserve.RightToLeft = RightToLeft.No;
      this.cmdNewReserve.Size = new Size(97, 47);
      this.cmdNewReserve.TabIndex = 489;
      this.cmdNewReserve.Text = "New Reser&vation";
      this.ToolTip1.SetToolTip((Control) this.cmdNewReserve, "Select for Transfer New Room");
      this.cmdNewReserve.UseVisualStyleBackColor = false;
      this.cmdNewReserve.Visible = false;
      this.cmdReservedView.BackColor = Color.FromArgb((int) byte.MaxValue, 128, 128);
      this.cmdReservedView.Cursor = Cursors.Default;
      this.cmdReservedView.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.cmdReservedView.ForeColor = SystemColors.ControlText;
      this.cmdReservedView.Image = (Image) componentResourceManager.GetObject("cmdReservedView.Image");
      this.cmdReservedView.Location = new Point(700, 9);
      this.cmdReservedView.Name = "cmdReservedView";
      this.cmdReservedView.RightToLeft = RightToLeft.No;
      this.cmdReservedView.Size = new Size(97, 47);
      this.cmdReservedView.TabIndex = 488;
      this.cmdReservedView.Text = "&Edit Reservation";
      this.cmdReservedView.TextAlign = ContentAlignment.BottomCenter;
      this.ToolTip1.SetToolTip((Control) this.cmdReservedView, "View Reservation List to Edit");
      this.cmdReservedView.UseVisualStyleBackColor = false;
      this.cmdPrint.BackColor = Color.FromArgb(192, 192, (int) byte.MaxValue);
      this.cmdPrint.Cursor = Cursors.Default;
      this.cmdPrint.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.cmdPrint.ForeColor = SystemColors.ControlText;
      this.cmdPrint.Image = (Image) componentResourceManager.GetObject("cmdPrint.Image");
      this.cmdPrint.Location = new Point(642, 465);
      this.cmdPrint.Name = "cmdPrint";
      this.cmdPrint.RightToLeft = RightToLeft.No;
      this.cmdPrint.Size = new Size(49, 55);
      this.cmdPrint.TabIndex = 471;
      this.cmdPrint.Text = "&Print Recipt";
      this.cmdPrint.TextAlign = ContentAlignment.BottomCenter;
      this.ToolTip1.SetToolTip((Control) this.cmdPrint, "Print Receipt");
      this.cmdPrint.UseVisualStyleBackColor = false;
      this.cmdClear.BackColor = Color.FromArgb(128, (int) byte.MaxValue, 128);
      this.cmdClear.Cursor = Cursors.Default;
      this.cmdClear.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.cmdClear.ForeColor = SystemColors.ControlText;
      this.cmdClear.Image = (Image) componentResourceManager.GetObject("cmdClear.Image");
      this.cmdClear.Location = new Point(695, 465);
      this.cmdClear.Name = "cmdClear";
      this.cmdClear.RightToLeft = RightToLeft.No;
      this.cmdClear.Size = new Size(49, 55);
      this.cmdClear.TabIndex = 472;
      this.cmdClear.Text = "&Clear";
      this.cmdClear.TextAlign = ContentAlignment.BottomCenter;
      this.ToolTip1.SetToolTip((Control) this.cmdClear, "To Clear Screen Data");
      this.cmdClear.UseVisualStyleBackColor = false;
      this.UnitFrame.BackColor = Color.FromArgb(128, 128, (int) byte.MaxValue);
      this.UnitFrame.Controls.Add((Control) this._lblBURoom_4);
      this.UnitFrame.Controls.Add((Control) this._lblBURoom_3);
      this.UnitFrame.Controls.Add((Control) this._lblBURoom_2);
      this.UnitFrame.Controls.Add((Control) this._lblBURoom_1);
      this.UnitFrame.Controls.Add((Control) this._lblBURoom_0);
      this.UnitFrame.Enabled = false;
      this.UnitFrame.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.UnitFrame.ForeColor = Color.Yellow;
      this.UnitFrame.Location = new Point(84, 200);
      this.UnitFrame.Name = "UnitFrame";
      this.UnitFrame.Padding = new Padding(0);
      this.UnitFrame.RightToLeft = RightToLeft.No;
      this.UnitFrame.Size = new Size(129, 49);
      this.UnitFrame.TabIndex = 578;
      this.UnitFrame.TabStop = false;
      this.UnitFrame.Text = "Unit- ";
      this.UnitFrame.Visible = false;
      this._lblBURoom_4.BackColor = Color.FromArgb(128, 128, (int) byte.MaxValue);
      this._lblBURoom_4.Cursor = Cursors.Default;
      this._lblBURoom_4.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this._lblBURoom_4.ForeColor = Color.White;
      this._lblBURoom_4.Location = new Point(48, 32);
      this._lblBURoom_4.Name = "_lblBURoom_4";
      this._lblBURoom_4.RightToLeft = RightToLeft.No;
      this._lblBURoom_4.Size = new Size(37, 15);
      this._lblBURoom_4.TabIndex = 583;
      this._lblBURoom_4.Text = "10101";
      this._lblBURoom_3.BackColor = Color.FromArgb(128, 128, (int) byte.MaxValue);
      this._lblBURoom_3.Cursor = Cursors.Default;
      this._lblBURoom_3.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this._lblBURoom_3.ForeColor = Color.White;
      this._lblBURoom_3.Location = new Point(8, 32);
      this._lblBURoom_3.Name = "_lblBURoom_3";
      this._lblBURoom_3.RightToLeft = RightToLeft.No;
      this._lblBURoom_3.Size = new Size(37, 15);
      this._lblBURoom_3.TabIndex = 582;
      this._lblBURoom_3.Text = "10101";
      this._lblBURoom_2.BackColor = Color.FromArgb(128, 128, (int) byte.MaxValue);
      this._lblBURoom_2.Cursor = Cursors.Default;
      this._lblBURoom_2.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this._lblBURoom_2.ForeColor = Color.White;
      this._lblBURoom_2.Location = new Point(88, 16);
      this._lblBURoom_2.Name = "_lblBURoom_2";
      this._lblBURoom_2.RightToLeft = RightToLeft.No;
      this._lblBURoom_2.Size = new Size(37, 15);
      this._lblBURoom_2.TabIndex = 581;
      this._lblBURoom_2.Text = "10101";
      this._lblBURoom_1.BackColor = Color.FromArgb(128, 128, (int) byte.MaxValue);
      this._lblBURoom_1.Cursor = Cursors.Default;
      this._lblBURoom_1.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this._lblBURoom_1.ForeColor = Color.White;
      this._lblBURoom_1.Location = new Point(47, 16);
      this._lblBURoom_1.Name = "_lblBURoom_1";
      this._lblBURoom_1.RightToLeft = RightToLeft.No;
      this._lblBURoom_1.Size = new Size(37, 15);
      this._lblBURoom_1.TabIndex = 580;
      this._lblBURoom_1.Text = "10101";
      this._lblBURoom_0.BackColor = Color.FromArgb(128, 128, (int) byte.MaxValue);
      this._lblBURoom_0.Cursor = Cursors.Default;
      this._lblBURoom_0.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this._lblBURoom_0.ForeColor = Color.White;
      this._lblBURoom_0.Location = new Point(5, 16);
      this._lblBURoom_0.Name = "_lblBURoom_0";
      this._lblBURoom_0.RightToLeft = RightToLeft.No;
      this._lblBURoom_0.Size = new Size(37, 15);
      this._lblBURoom_0.TabIndex = 579;
      this._lblBURoom_0.Text = "10101";
      this.cmdExisting.BackColor = Color.FromArgb((int) byte.MaxValue, 192, 192);
      this.cmdExisting.Cursor = Cursors.Default;
      this.cmdExisting.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.cmdExisting.ForeColor = SystemColors.ControlText;
      this.cmdExisting.Location = new Point(152, 64);
      this.cmdExisting.Name = "cmdExisting";
      this.cmdExisting.RightToLeft = RightToLeft.No;
      this.cmdExisting.Size = new Size(49, 25);
      this.cmdExisting.TabIndex = 11;
      this.cmdExisting.Text = "&Existing";
      this.cmdExisting.UseVisualStyleBackColor = false;
      this.MaskEdBox2.AllowPromptAsInput = false;
      this.MaskEdBox2.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.MaskEdBox2.ForeColor = Color.Blue;
      this.MaskEdBox2.Location = new Point(328, 216);
      this.MaskEdBox2.Mask = "##/##/####";
      this.MaskEdBox2.Name = "MaskEdBox2";
      this.MaskEdBox2.Size = new Size(81, 20);
      this.MaskEdBox2.TabIndex = 30;
      this.MaskEdBox4.AllowPromptAsInput = false;
      this.MaskEdBox4.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.MaskEdBox4.ForeColor = Color.Blue;
      this.MaskEdBox4.Location = new Point(320, 256);
      this.MaskEdBox4.Mask = "##/##/####";
      this.MaskEdBox4.Name = "MaskEdBox4";
      this.MaskEdBox4.Size = new Size(81, 20);
      this.MaskEdBox4.TabIndex = 33;
      this.lblRType.BackColor = Color.Blue;
      this.lblRType.Cursor = Cursors.Default;
      this.lblRType.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.lblRType.ForeColor = Color.White;
      this.lblRType.Location = new Point(8, 200);
      this.lblRType.Name = "lblRType";
      this.lblRType.RightToLeft = RightToLeft.No;
      this.lblRType.Size = new Size(65, 25);
      this.lblRType.TabIndex = 584;
      this.lblRType.TextAlign = ContentAlignment.TopRight;
      this.lblOldDepositAmount.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 128);
      this.lblOldDepositAmount.BorderStyle = BorderStyle.Fixed3D;
      this.lblOldDepositAmount.Cursor = Cursors.Default;
      this.lblOldDepositAmount.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.lblOldDepositAmount.ForeColor = SystemColors.ControlText;
      this.lblOldDepositAmount.Location = new Point(144, 376);
      this.lblOldDepositAmount.Name = "lblOldDepositAmount";
      this.lblOldDepositAmount.RightToLeft = RightToLeft.No;
      this.lblOldDepositAmount.Size = new Size(57, 17);
      this.lblOldDepositAmount.TabIndex = 364;
      this.lblOldDepositAmount.TextAlign = ContentAlignment.TopCenter;
      this.lblOldDepositAmount.Visible = false;
      this.lblOldDeposit.BackColor = Color.FromArgb(128, (int) byte.MaxValue, (int) byte.MaxValue);
      this.lblOldDeposit.Cursor = Cursors.Default;
      this.lblOldDeposit.Font = new Font("Arial Black", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.lblOldDeposit.ForeColor = SystemColors.ControlText;
      this.lblOldDeposit.Location = new Point(134, 360);
      this.lblOldDeposit.Name = "lblOldDeposit";
      this.lblOldDeposit.RightToLeft = RightToLeft.No;
      this.lblOldDeposit.Size = new Size(73, 17);
      this.lblOldDeposit.TabIndex = 363;
      this.lblOldDeposit.Text = "Old Deposit";
      this.lblOldDeposit.Visible = false;
      this.lblDifference.BackColor = Color.FromArgb(128, (int) byte.MaxValue, (int) byte.MaxValue);
      this.lblDifference.Cursor = Cursors.Default;
      this.lblDifference.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.lblDifference.ForeColor = Color.Blue;
      this.lblDifference.Location = new Point(8, 376);
      this.lblDifference.Name = "lblDifference";
      this.lblDifference.RightToLeft = RightToLeft.No;
      this.lblDifference.Size = new Size(57, 17);
      this.lblDifference.TabIndex = 362;
      this.lblDifference.Text = "Collect ";
      this.lblDifference.TextAlign = ContentAlignment.TopRight;
      this.lblDifference.Visible = false;
      this.lblDiffAmount.BackColor = Color.White;
      this.lblDiffAmount.BorderStyle = BorderStyle.Fixed3D;
      this.lblDiffAmount.Cursor = Cursors.Default;
      this.lblDiffAmount.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.lblDiffAmount.ForeColor = Color.Red;
      this.lblDiffAmount.Location = new Point(72, 376);
      this.lblDiffAmount.Name = "lblDiffAmount";
      this.lblDiffAmount.RightToLeft = RightToLeft.No;
      this.lblDiffAmount.Size = new Size(65, 21);
      this.lblDiffAmount.TabIndex = 361;
      this.lblDiffAmount.TextAlign = ContentAlignment.TopCenter;
      this.lblDiffAmount.Visible = false;
      this.lblOldRoomNo.BackColor = Color.FromArgb(128, (int) byte.MaxValue, (int) byte.MaxValue);
      this.lblOldRoomNo.Cursor = Cursors.Default;
      this.lblOldRoomNo.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.lblOldRoomNo.ForeColor = SystemColors.ControlText;
      this.lblOldRoomNo.Location = new Point(96, 176);
      this.lblOldRoomNo.Name = "lblOldRoomNo";
      this.lblOldRoomNo.RightToLeft = RightToLeft.No;
      this.lblOldRoomNo.Size = new Size(57, 17);
      this.lblOldRoomNo.TabIndex = 360;
      this.lblOldRoomNo.Visible = false;
      this.lblOldRoom.BackColor = Color.FromArgb(128, (int) byte.MaxValue, (int) byte.MaxValue);
      this.lblOldRoom.Cursor = Cursors.Default;
      this.lblOldRoom.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.lblOldRoom.ForeColor = SystemColors.ControlText;
      this.lblOldRoom.Location = new Point(8, 176);
      this.lblOldRoom.Name = "lblOldRoom";
      this.lblOldRoom.RightToLeft = RightToLeft.No;
      this.lblOldRoom.Size = new Size(65, 17);
      this.lblOldRoom.TabIndex = 358;
      this.lblOldRoom.Text = "Old Room";
      this.lblOldRoom.TextAlign = ContentAlignment.TopRight;
      this.lblOldRoom.Visible = false;
      this.Label12.BackColor = Color.FromArgb(128, (int) byte.MaxValue, (int) byte.MaxValue);
      this.Label12.Cursor = Cursors.Default;
      this.Label12.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label12.ForeColor = SystemColors.ControlText;
      this.Label12.Location = new Point(8, 93);
      this.Label12.Name = "Label12";
      this.Label12.RightToLeft = RightToLeft.No;
      this.Label12.Size = new Size(193, 14);
      this.Label12.TabIndex = 37;
      this.Label12.Text = "First Name";
      this.Label12.TextAlign = ContentAlignment.TopCenter;
      this.lblOldRoomType.BackColor = Color.FromArgb(128, (int) byte.MaxValue, (int) byte.MaxValue);
      this.lblOldRoomType.Cursor = Cursors.Default;
      this.lblOldRoomType.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.lblOldRoomType.ForeColor = SystemColors.ControlText;
      this.lblOldRoomType.Location = new Point(160, 176);
      this.lblOldRoomType.Name = "lblOldRoomType";
      this.lblOldRoomType.RightToLeft = RightToLeft.No;
      this.lblOldRoomType.Size = new Size(49, 17);
      this.lblOldRoomType.TabIndex = 359;
      this.lblOldRoomType.Visible = false;
      this.Label13.BackColor = Color.FromArgb(128, (int) byte.MaxValue, (int) byte.MaxValue);
      this.Label13.Cursor = Cursors.Default;
      this.Label13.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label13.ForeColor = SystemColors.ControlText;
      this.Label13.Location = new Point(16, 312);
      this.Label13.Name = "Label13";
      this.Label13.RightToLeft = RightToLeft.No;
      this.Label13.Size = new Size(73, 17);
      this.Label13.TabIndex = 38;
      this.Label13.Text = "No.Of Days ";
      this.Label13.TextAlign = ContentAlignment.TopRight;
      this.lblBookingRoomNo.BackColor = Color.FromArgb(128, (int) byte.MaxValue, (int) byte.MaxValue);
      this.lblBookingRoomNo.Cursor = Cursors.Default;
      this.lblBookingRoomNo.Font = new Font("Times New Roman", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.lblBookingRoomNo.ForeColor = Color.Blue;
      this.lblBookingRoomNo.Location = new Point(104, 232);
      this.lblBookingRoomNo.Name = "lblBookingRoomNo";
      this.lblBookingRoomNo.RightToLeft = RightToLeft.No;
      this.lblBookingRoomNo.Size = new Size(97, 17);
      this.lblBookingRoomNo.TabIndex = 36;
      this.Label11.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.Label11.Cursor = Cursors.Default;
      this.Label11.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label11.ForeColor = SystemColors.ControlText;
      this.Label11.Location = new Point(240, 256);
      this.Label11.Name = "Label11";
      this.Label11.RightToLeft = RightToLeft.No;
      this.Label11.Size = new Size(65, 17);
      this.Label11.TabIndex = 35;
      this.Label11.Text = "End Date";
      this.Label11.TextAlign = ContentAlignment.TopRight;
      this.Label9.BackColor = Color.FromArgb(128, (int) byte.MaxValue, (int) byte.MaxValue);
      this.Label9.Cursor = Cursors.Default;
      this.Label9.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label9.ForeColor = SystemColors.ControlText;
      this.Label9.Location = new Point(8, 288);
      this.Label9.Name = "Label9";
      this.Label9.RightToLeft = RightToLeft.No;
      this.Label9.Size = new Size(81, 25);
      this.Label9.TabIndex = 34;
      this.Label9.Text = "Booking End  ";
      this.Label9.TextAlign = ContentAlignment.TopRight;
      this.Label2.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.Label2.Cursor = Cursors.Default;
      this.Label2.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label2.ForeColor = SystemColors.ControlText;
      this.Label2.Location = new Point(248, 216);
      this.Label2.Name = "Label2";
      this.Label2.RightToLeft = RightToLeft.No;
      this.Label2.Size = new Size(65, 17);
      this.Label2.TabIndex = 32;
      this.Label2.Text = "End Date";
      this.Label2.TextAlign = ContentAlignment.TopRight;
      this.ReservationFrame.BackColor = Color.FromArgb(128, (int) byte.MaxValue, (int) byte.MaxValue);
      this.ReservationFrame.Controls.Add((Control) this.UnitFrame);
      this.ReservationFrame.Controls.Add((Control) this.cmdExisting);
      this.ReservationFrame.Controls.Add((Control) this.txtNoOfDays);
      this.ReservationFrame.Controls.Add((Control) this.txtFirstName);
      this.ReservationFrame.Controls.Add((Control) this.txtDeposit);
      this.ReservationFrame.Controls.Add((Control) this.txtSurName);
      this.ReservationFrame.Controls.Add((Control) this.txtClientID);
      this.ReservationFrame.Controls.Add((Control) this.txtReservationRef);
      this.ReservationFrame.Controls.Add((Control) this.mskBookingStart);
      this.ReservationFrame.Controls.Add((Control) this.MaskEdBox2);
      this.ReservationFrame.Controls.Add((Control) this.mskBookingEnd);
      this.ReservationFrame.Controls.Add((Control) this.MaskEdBox4);
      this.ReservationFrame.Controls.Add((Control) this.lblRType);
      this.ReservationFrame.Controls.Add((Control) this.lblOldDepositAmount);
      this.ReservationFrame.Controls.Add((Control) this.lblOldDeposit);
      this.ReservationFrame.Controls.Add((Control) this.lblDifference);
      this.ReservationFrame.Controls.Add((Control) this.lblDiffAmount);
      this.ReservationFrame.Controls.Add((Control) this.lblOldRoomNo);
      this.ReservationFrame.Controls.Add((Control) this.lblOldRoomType);
      this.ReservationFrame.Controls.Add((Control) this.lblOldRoom);
      this.ReservationFrame.Controls.Add((Control) this.Label13);
      this.ReservationFrame.Controls.Add((Control) this.Label12);
      this.ReservationFrame.Controls.Add((Control) this.lblBookingRoomNo);
      this.ReservationFrame.Controls.Add((Control) this.Label11);
      this.ReservationFrame.Controls.Add((Control) this.Label9);
      this.ReservationFrame.Controls.Add((Control) this.Label2);
      this.ReservationFrame.Controls.Add((Control) this.Label1);
      this.ReservationFrame.Controls.Add((Control) this.Label7);
      this.ReservationFrame.Controls.Add((Control) this.Label21);
      this.ReservationFrame.Controls.Add((Control) this.Label5);
      this.ReservationFrame.Controls.Add((Control) this.Label3);
      this.ReservationFrame.Controls.Add((Control) this.Label6);
      this.ReservationFrame.Enabled = false;
      this.ReservationFrame.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.ReservationFrame.ForeColor = Color.Red;
      this.ReservationFrame.Location = new Point(580, 57);
      this.ReservationFrame.Name = "ReservationFrame";
      this.ReservationFrame.Padding = new Padding(0);
      this.ReservationFrame.RightToLeft = RightToLeft.No;
      this.ReservationFrame.Size = new Size(217, 401);
      this.ReservationFrame.TabIndex = 485;
      this.ReservationFrame.TabStop = false;
      this.ReservationFrame.Text = "RESERVATION :";
      this.ReservationFrame.Visible = false;
      this.Label1.BackColor = Color.FromArgb(128, (int) byte.MaxValue, (int) byte.MaxValue);
      this.Label1.Cursor = Cursors.Default;
      this.Label1.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label1.ForeColor = Color.FromArgb(64, 64, 64);
      this.Label1.Location = new Point(8, 256);
      this.Label1.Name = "Label1";
      this.Label1.RightToLeft = RightToLeft.No;
      this.Label1.Size = new Size(81, 25);
      this.Label1.TabIndex = 31;
      this.Label1.Text = "Booking Start ";
      this.Label1.TextAlign = ContentAlignment.TopRight;
      this.Label7.BackColor = Color.FromArgb(128, (int) byte.MaxValue, (int) byte.MaxValue);
      this.Label7.Cursor = Cursors.Default;
      this.Label7.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label7.ForeColor = Color.FromArgb((int) byte.MaxValue, 0, (int) byte.MaxValue);
      this.Label7.Location = new Point(4, 232);
      this.Label7.Name = "Label7";
      this.Label7.RightToLeft = RightToLeft.No;
      this.Label7.Size = new Size(80, 17);
      this.Label7.TabIndex = 29;
      this.Label7.Text = "Room No.";
      this.Label7.TextAlign = ContentAlignment.TopRight;
      this.Label21.BackColor = Color.FromArgb(128, (int) byte.MaxValue, (int) byte.MaxValue);
      this.Label21.Cursor = Cursors.Default;
      this.Label21.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label21.ForeColor = Color.Red;
      this.Label21.Location = new Point(8, 344);
      this.Label21.Name = "Label21";
      this.Label21.RightToLeft = RightToLeft.No;
      this.Label21.Size = new Size(57, 17);
      this.Label21.TabIndex = 28;
      this.Label21.Text = "Deposit ";
      this.Label21.TextAlign = ContentAlignment.TopRight;
      this.Label5.BackColor = Color.FromArgb(128, (int) byte.MaxValue, (int) byte.MaxValue);
      this.Label5.Cursor = Cursors.Default;
      this.Label5.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label5.ForeColor = SystemColors.ControlText;
      this.Label5.Location = new Point(8, 128);
      this.Label5.Name = "Label5";
      this.Label5.RightToLeft = RightToLeft.No;
      this.Label5.Size = new Size(193, 17);
      this.Label5.TabIndex = 27;
      this.Label5.Text = "SurName ";
      this.Label5.TextAlign = ContentAlignment.TopCenter;
      this.Label3.BackColor = Color.FromArgb(128, (int) byte.MaxValue, (int) byte.MaxValue);
      this.Label3.Cursor = Cursors.Default;
      this.Label3.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label3.ForeColor = Color.Blue;
      this.Label3.Location = new Point(8, 64);
      this.Label3.Name = "Label3";
      this.Label3.RightToLeft = RightToLeft.No;
      this.Label3.Size = new Size(57, 17);
      this.Label3.TabIndex = 26;
      this.Label3.Text = "Guest ID   ";
      this.Label3.TextAlign = ContentAlignment.TopRight;
      this.Label6.BackColor = Color.FromArgb(128, (int) byte.MaxValue, (int) byte.MaxValue);
      this.Label6.Cursor = Cursors.Default;
      this.Label6.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label6.ForeColor = Color.FromArgb(0, 128, 0);
      this.Label6.Location = new Point(8, 16);
      this.Label6.Name = "Label6";
      this.Label6.RightToLeft = RightToLeft.No;
      this.Label6.Size = new Size(193, 17);
      this.Label6.TabIndex = 25;
      this.Label6.Text = "Reservation Reference : ";
      this.Label6.TextAlign = ContentAlignment.TopCenter;
      this.txtRoomType.AcceptsReturn = true;
      this.txtRoomType.BackColor = SystemColors.Window;
      this.txtRoomType.Cursor = Cursors.IBeam;
      this.txtRoomType.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtRoomType.ForeColor = SystemColors.WindowText;
      this.txtRoomType.Location = new Point(452, 1);
      this.txtRoomType.MaxLength = 0;
      this.txtRoomType.Name = "txtRoomType";
      this.txtRoomType.RightToLeft = RightToLeft.No;
      this.txtRoomType.Size = new Size(25, 20);
      this.txtRoomType.TabIndex = 479;
      this.txtRoomType.TextAlign = HorizontalAlignment.Center;
      this.txtRoomType.Visible = false;
      this.lblBuildingType.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.lblBuildingType.Cursor = Cursors.Default;
      this.lblBuildingType.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.lblBuildingType.ForeColor = Color.Blue;
      this.lblBuildingType.Location = new Point(204, 1);
      this.lblBuildingType.Name = "lblBuildingType";
      this.lblBuildingType.RightToLeft = RightToLeft.No;
      this.lblBuildingType.Size = new Size(81, 25);
      this.lblBuildingType.TabIndex = 490;
      this.lblMessage.BackColor = Color.White;
      this.lblMessage.Cursor = Cursors.Default;
      this.lblMessage.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.lblMessage.ForeColor = Color.Red;
      this.lblMessage.Location = new Point(12, 521);
      this.lblMessage.Name = "lblMessage";
      this.lblMessage.RightToLeft = RightToLeft.No;
      this.lblMessage.Size = new Size(673, 17);
      this.lblMessage.TabIndex = 487;
      this.lblMessage.Text = "Label4";
      this.lblMessage.TextAlign = ContentAlignment.TopCenter;
      this.lbBuilding.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.lbBuilding.Cursor = Cursors.Default;
      this.lbBuilding.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.lbBuilding.ForeColor = SystemColors.ControlText;
      this.lbBuilding.Location = new Point(84, 1);
      this.lbBuilding.Name = "lbBuilding";
      this.lbBuilding.RightToLeft = RightToLeft.No;
      this.lbBuilding.Size = new Size(57, 17);
      this.lbBuilding.TabIndex = 484;
      this.lbBuilding.Text = "Building";
      this.lbBuilding.TextAlign = ContentAlignment.TopRight;
      this.Label8.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.Label8.Cursor = Cursors.Default;
      this.Label8.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label8.ForeColor = SystemColors.ControlText;
      this.Label8.Location = new Point(284, 1);
      this.Label8.Name = "Label8";
      this.Label8.RightToLeft = RightToLeft.No;
      this.Label8.Size = new Size(81, 17);
      this.Label8.TabIndex = 482;
      this.Label8.Text = "Room Type ";
      this.Label8.TextAlign = ContentAlignment.TopRight;
      this.Label17.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.Label17.Cursor = Cursors.Default;
      this.Label17.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label17.ForeColor = SystemColors.ControlText;
      this.Label17.Location = new Point(60, 25);
      this.Label17.Name = "Label17";
      this.Label17.RightToLeft = RightToLeft.No;
      this.Label17.Size = new Size(81, 17);
      this.Label17.TabIndex = 481;
      this.Label17.Text = "Start Date";
      this.Label17.TextAlign = ContentAlignment.TopRight;
      this.Label18.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.Label18.Cursor = Cursors.Default;
      this.Label18.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label18.ForeColor = SystemColors.ControlText;
      this.Label18.Location = new Point(292, 25);
      this.Label18.Name = "Label18";
      this.Label18.RightToLeft = RightToLeft.No;
      this.Label18.Size = new Size(65, 17);
      this.Label18.TabIndex = 480;
      this.Label18.Text = "End Date";
      this.Label18.TextAlign = ContentAlignment.TopRight;
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(800, 595);
      this.Controls.Add((Control) this.ReservationFrame);
      this.Controls.Add((Control) this.txtRoomType);
      this.Controls.Add((Control) this.lblBuildingType);
      this.Controls.Add((Control) this.lblMessage);
      this.Controls.Add((Control) this.lbBuilding);
      this.Controls.Add((Control) this.Label8);
      this.Controls.Add((Control) this.Label17);
      this.Controls.Add((Control) this.Label18);
      this.Controls.Add((Control) this.mskEndDate);
      this.Controls.Add((Control) this.cmdReturn);
      this.Controls.Add((Control) this.mskStartDate);
      this.Controls.Add((Control) this.cmdView);
      this.Controls.Add((Control) this.cboRoomType);
      this.Controls.Add((Control) this.cmdConfirm);
      this.Controls.Add((Control) this.cboBuilding);
      this.Controls.Add((Control) this.cmdNewReserve);
      this.Controls.Add((Control) this.cmdReservedView);
      this.Controls.Add((Control) this.cmdPrint);
      this.Controls.Add((Control) this.cmdClear);
      this.Name = "Form_ReservationDMS";
      this.StartPosition = FormStartPosition.CenterScreen;
      this.Text = "ACCOMMODATION MANAGEMENT SYSTEM";
      this.Load += new EventHandler(this.Form_ReservationDMS_Load);
      this.FormClosing += new FormClosingEventHandler(this.Form_ReservationDMS_FormClosing);
      this.UnitFrame.ResumeLayout(false);
      this.ReservationFrame.ResumeLayout(false);
      this.ReservationFrame.PerformLayout();
      this.ResumeLayout(false);
      this.PerformLayout();
    }

    public Form_ReservationDMS() => this.InitializeComponent();

    private void cmdReturn_Click(object sender, EventArgs e)
    {
      this.Visible = false;
      ModDoorLockSystem.Form_OperationDMS_Ptr.Visible = true;
    }

    private void Form_ReservationDMS_FormClosing(object sender, FormClosingEventArgs e)
    {
      Application.Exit();
    }

    private void Form_ReservationDMS_Load(object sender, EventArgs e)
    {
    }

    private void cmdConfirm_Click(object sender, EventArgs e)
    {
    }

    private void cmdView_Click(object sender, EventArgs e)
    {
    }
  }
}
