// Decompiled with JetBrains decompiler
// Type: AMS.Form_CancelCardDMS
// Assembly: AMS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 99EBC956-E2B8-4955-9E76-E3E000435543
// Assembly location: C:\Users\Administrator\Desktop\birchridge\AMS 2017\AMS.exe

using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

#nullable disable
namespace AMS
{
  public class Form_CancelCardDMS : Form
  {
    private IContainer components;
    public TextBox txtEndTime;
    public TextBox txtEndDate;
    public ToolTip ToolTip1;
    public Button cmdReturn;
    public TextBox txtCardType;
    public Button cmdCancel;
    public TextBox txtStartTime;
    public TextBox txtStartDate;
    public TextBox txtCountry;
    public GroupBox IssueCardFrame;
    public TextBox txtSex;
    public TextBox txtClientID;
    public TextBox txtRemark;
    public TextBox txtContact;
    public TextBox txtAddress;
    public TextBox txtNationality;
    public TextBox txtIdentity;
    public TextBox txtSurName;
    public TextBox txtFirstName;
    public TextBox txtCardNo;
    public Label Label3;
    public Label lbInTime;
    public Label lbOutTime;
    public Label Label27;
    public Label Label11;
    public Label Label10;
    public Label Label9;
    public Label Label8;
    public Label _Label7_0;
    public Label Label6;
    public Label lbValidEnd;
    public Label Label24;
    public Label Label4;
    public Label Label5;
    public Label Label28;
    public Label lbBuilding;
    public Label lblMessage1;
    public Label Label1;
    public Label lblMessage;
    public Label Label14;
    public Label lbReadCardHeader;
    public Label lbFloor;
    public GroupBox Frame2;
    public Timer Timer1;
    public GroupBox Frame1;
    public GroupBox ZoneFrame;
    public TextBox txtZoneNo;
    public Label lbZoneNo;
    public TextBox txtBuilding;
    public GroupBox RoomFrame;
    public TextBox txtRoomNo;
    public Label Label2;
    public GroupBox FloorFrame;
    public TextBox txtFloorNo;

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.components = (IContainer) new System.ComponentModel.Container();
      ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (Form_CancelCardDMS));
      this.txtEndTime = new TextBox();
      this.txtEndDate = new TextBox();
      this.ToolTip1 = new ToolTip(this.components);
      this.cmdReturn = new Button();
      this.txtCardType = new TextBox();
      this.cmdCancel = new Button();
      this.txtStartTime = new TextBox();
      this.txtStartDate = new TextBox();
      this.txtCountry = new TextBox();
      this.IssueCardFrame = new GroupBox();
      this.txtSex = new TextBox();
      this.txtClientID = new TextBox();
      this.txtRemark = new TextBox();
      this.txtContact = new TextBox();
      this.txtAddress = new TextBox();
      this.txtNationality = new TextBox();
      this.txtIdentity = new TextBox();
      this.txtSurName = new TextBox();
      this.txtFirstName = new TextBox();
      this.txtCardNo = new TextBox();
      this.Label3 = new Label();
      this.lbInTime = new Label();
      this.lbOutTime = new Label();
      this.Label27 = new Label();
      this.Label11 = new Label();
      this.Label10 = new Label();
      this.Label9 = new Label();
      this.Label8 = new Label();
      this._Label7_0 = new Label();
      this.Label6 = new Label();
      this.lbValidEnd = new Label();
      this.Label24 = new Label();
      this.Label4 = new Label();
      this.Label5 = new Label();
      this.Label28 = new Label();
      this.lbBuilding = new Label();
      this.lblMessage1 = new Label();
      this.Label1 = new Label();
      this.lblMessage = new Label();
      this.Label14 = new Label();
      this.lbReadCardHeader = new Label();
      this.lbFloor = new Label();
      this.Frame2 = new GroupBox();
      this.Timer1 = new Timer(this.components);
      this.Frame1 = new GroupBox();
      this.ZoneFrame = new GroupBox();
      this.txtZoneNo = new TextBox();
      this.lbZoneNo = new Label();
      this.txtBuilding = new TextBox();
      this.RoomFrame = new GroupBox();
      this.txtRoomNo = new TextBox();
      this.Label2 = new Label();
      this.FloorFrame = new GroupBox();
      this.txtFloorNo = new TextBox();
      this.IssueCardFrame.SuspendLayout();
      this.Frame2.SuspendLayout();
      this.Frame1.SuspendLayout();
      this.ZoneFrame.SuspendLayout();
      this.RoomFrame.SuspendLayout();
      this.FloorFrame.SuspendLayout();
      this.SuspendLayout();
      this.txtEndTime.AcceptsReturn = true;
      this.txtEndTime.BackColor = Color.FromArgb(192, (int) byte.MaxValue, (int) byte.MaxValue);
      this.txtEndTime.Cursor = Cursors.IBeam;
      this.txtEndTime.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtEndTime.ForeColor = Color.Blue;
      this.txtEndTime.Location = new Point(843, 158);
      this.txtEndTime.Margin = new Padding(4, 4, 4, 4);
      this.txtEndTime.MaxLength = 0;
      this.txtEndTime.Name = "txtEndTime";
      this.txtEndTime.ReadOnly = true;
      this.txtEndTime.RightToLeft = RightToLeft.No;
      this.txtEndTime.Size = new Size(107, 23);
      this.txtEndTime.TabIndex = 46;
      this.txtEndDate.AcceptsReturn = true;
      this.txtEndDate.BackColor = Color.FromArgb(192, (int) byte.MaxValue, (int) byte.MaxValue);
      this.txtEndDate.Cursor = Cursors.IBeam;
      this.txtEndDate.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtEndDate.ForeColor = Color.Blue;
      this.txtEndDate.Location = new Point(843, 118);
      this.txtEndDate.Margin = new Padding(4, 4, 4, 4);
      this.txtEndDate.MaxLength = 0;
      this.txtEndDate.Name = "txtEndDate";
      this.txtEndDate.ReadOnly = true;
      this.txtEndDate.RightToLeft = RightToLeft.No;
      this.txtEndDate.Size = new Size(107, 23);
      this.txtEndDate.TabIndex = 45;
      this.cmdReturn.BackColor = Color.FromArgb(0, 192, 192);
      this.cmdReturn.Cursor = Cursors.Default;
      this.cmdReturn.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.cmdReturn.ForeColor = SystemColors.ControlText;
      this.cmdReturn.Image = (Image) componentResourceManager.GetObject("cmdReturn.Image");
      this.cmdReturn.Location = new Point(512, 20);
      this.cmdReturn.Margin = new Padding(4, 4, 4, 4);
      this.cmdReturn.Name = "cmdReturn";
      this.cmdReturn.RightToLeft = RightToLeft.No;
      this.cmdReturn.Size = new Size(151, 48);
      this.cmdReturn.TabIndex = 33;
      this.cmdReturn.Text = "Retur&n";
      this.cmdReturn.TextAlign = ContentAlignment.BottomCenter;
      this.ToolTip1.SetToolTip((Control) this.cmdReturn, "Return to Admin Screen");
      this.cmdReturn.UseVisualStyleBackColor = false;
      this.cmdReturn.Click += new EventHandler(this.cmdReturn_Click);
      this.txtCardType.AcceptsReturn = true;
      this.txtCardType.BackColor = Color.FromArgb((int) byte.MaxValue, 224, 192);
      this.txtCardType.Cursor = Cursors.IBeam;
      this.txtCardType.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtCardType.ForeColor = Color.Black;
      this.txtCardType.Location = new Point(139, 30);
      this.txtCardType.Margin = new Padding(4, 4, 4, 4);
      this.txtCardType.MaxLength = 0;
      this.txtCardType.Name = "txtCardType";
      this.txtCardType.ReadOnly = true;
      this.txtCardType.RightToLeft = RightToLeft.No;
      this.txtCardType.Size = new Size(192, 26);
      this.txtCardType.TabIndex = 37;
      this.ToolTip1.SetToolTip((Control) this.txtCardType, "Card Type");
      this.cmdCancel.BackColor = Color.FromArgb(0, 192, 0);
      this.cmdCancel.Cursor = Cursors.Default;
      this.cmdCancel.Enabled = false;
      this.cmdCancel.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.cmdCancel.ForeColor = SystemColors.ControlText;
      this.cmdCancel.Image = (Image) componentResourceManager.GetObject("cmdCancel.Image");
      this.cmdCancel.Location = new Point(309, 20);
      this.cmdCancel.Margin = new Padding(4, 4, 4, 4);
      this.cmdCancel.Name = "cmdCancel";
      this.cmdCancel.RightToLeft = RightToLeft.No;
      this.cmdCancel.Size = new Size(151, 48);
      this.cmdCancel.TabIndex = 48;
      this.cmdCancel.Text = "&Cancel";
      this.cmdCancel.TextAlign = ContentAlignment.BottomCenter;
      this.ToolTip1.SetToolTip((Control) this.cmdCancel, "Confirm Cancel");
      this.cmdCancel.UseVisualStyleBackColor = false;
      this.txtStartTime.AcceptsReturn = true;
      this.txtStartTime.BackColor = Color.FromArgb(192, (int) byte.MaxValue, (int) byte.MaxValue);
      this.txtStartTime.Cursor = Cursors.IBeam;
      this.txtStartTime.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtStartTime.ForeColor = Color.Blue;
      this.txtStartTime.Location = new Point(565, 158);
      this.txtStartTime.Margin = new Padding(4, 4, 4, 4);
      this.txtStartTime.MaxLength = 0;
      this.txtStartTime.Name = "txtStartTime";
      this.txtStartTime.ReadOnly = true;
      this.txtStartTime.RightToLeft = RightToLeft.No;
      this.txtStartTime.Size = new Size(117, 23);
      this.txtStartTime.TabIndex = 44;
      this.txtStartDate.AcceptsReturn = true;
      this.txtStartDate.BackColor = Color.FromArgb(192, (int) byte.MaxValue, (int) byte.MaxValue);
      this.txtStartDate.Cursor = Cursors.IBeam;
      this.txtStartDate.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtStartDate.ForeColor = Color.Blue;
      this.txtStartDate.Location = new Point(565, 118);
      this.txtStartDate.Margin = new Padding(4, 4, 4, 4);
      this.txtStartDate.MaxLength = 0;
      this.txtStartDate.Name = "txtStartDate";
      this.txtStartDate.ReadOnly = true;
      this.txtStartDate.RightToLeft = RightToLeft.No;
      this.txtStartDate.Size = new Size(117, 23);
      this.txtStartDate.TabIndex = 43;
      this.txtCountry.AcceptsReturn = true;
      this.txtCountry.BackColor = Color.FromArgb(192, (int) byte.MaxValue, (int) byte.MaxValue);
      this.txtCountry.Cursor = Cursors.IBeam;
      this.txtCountry.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtCountry.ForeColor = Color.Blue;
      this.txtCountry.Location = new Point(565, 236);
      this.txtCountry.Margin = new Padding(4, 4, 4, 4);
      this.txtCountry.MaxLength = 0;
      this.txtCountry.Name = "txtCountry";
      this.txtCountry.RightToLeft = RightToLeft.No;
      this.txtCountry.Size = new Size(203, 23);
      this.txtCountry.TabIndex = 42;
      this.IssueCardFrame.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.IssueCardFrame.Controls.Add((Control) this.txtEndTime);
      this.IssueCardFrame.Controls.Add((Control) this.txtEndDate);
      this.IssueCardFrame.Controls.Add((Control) this.txtStartTime);
      this.IssueCardFrame.Controls.Add((Control) this.txtStartDate);
      this.IssueCardFrame.Controls.Add((Control) this.txtCountry);
      this.IssueCardFrame.Controls.Add((Control) this.txtSex);
      this.IssueCardFrame.Controls.Add((Control) this.txtClientID);
      this.IssueCardFrame.Controls.Add((Control) this.txtRemark);
      this.IssueCardFrame.Controls.Add((Control) this.txtContact);
      this.IssueCardFrame.Controls.Add((Control) this.txtAddress);
      this.IssueCardFrame.Controls.Add((Control) this.txtNationality);
      this.IssueCardFrame.Controls.Add((Control) this.txtIdentity);
      this.IssueCardFrame.Controls.Add((Control) this.txtSurName);
      this.IssueCardFrame.Controls.Add((Control) this.txtFirstName);
      this.IssueCardFrame.Controls.Add((Control) this.txtCardNo);
      this.IssueCardFrame.Controls.Add((Control) this.Label3);
      this.IssueCardFrame.Controls.Add((Control) this.lbInTime);
      this.IssueCardFrame.Controls.Add((Control) this.lbOutTime);
      this.IssueCardFrame.Controls.Add((Control) this.Label27);
      this.IssueCardFrame.Controls.Add((Control) this.Label11);
      this.IssueCardFrame.Controls.Add((Control) this.Label10);
      this.IssueCardFrame.Controls.Add((Control) this.Label9);
      this.IssueCardFrame.Controls.Add((Control) this.Label8);
      this.IssueCardFrame.Controls.Add((Control) this._Label7_0);
      this.IssueCardFrame.Controls.Add((Control) this.Label6);
      this.IssueCardFrame.Controls.Add((Control) this.lbValidEnd);
      this.IssueCardFrame.Controls.Add((Control) this.Label24);
      this.IssueCardFrame.Controls.Add((Control) this.Label4);
      this.IssueCardFrame.Controls.Add((Control) this.Label5);
      this.IssueCardFrame.Controls.Add((Control) this.Label28);
      this.IssueCardFrame.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.IssueCardFrame.ForeColor = SystemColors.ControlText;
      this.IssueCardFrame.Location = new Point(16, 223);
      this.IssueCardFrame.Margin = new Padding(4, 4, 4, 4);
      this.IssueCardFrame.Name = "IssueCardFrame";
      this.IssueCardFrame.Padding = new Padding(0);
      this.IssueCardFrame.RightToLeft = RightToLeft.No;
      this.IssueCardFrame.Size = new Size(983, 356);
      this.IssueCardFrame.TabIndex = 49;
      this.IssueCardFrame.TabStop = false;
      this.IssueCardFrame.Text = "READ DATA :";
      this.txtSex.AcceptsReturn = true;
      this.txtSex.BackColor = Color.FromArgb(192, (int) byte.MaxValue, (int) byte.MaxValue);
      this.txtSex.Cursor = Cursors.IBeam;
      this.txtSex.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtSex.ForeColor = Color.Blue;
      this.txtSex.Location = new Point(139, 79);
      this.txtSex.Margin = new Padding(4, 4, 4, 4);
      this.txtSex.MaxLength = 0;
      this.txtSex.Name = "txtSex";
      this.txtSex.ReadOnly = true;
      this.txtSex.RightToLeft = RightToLeft.No;
      this.txtSex.Size = new Size(64, 23);
      this.txtSex.TabIndex = 41;
      this.txtClientID.AcceptsReturn = true;
      this.txtClientID.BackColor = Color.FromArgb(192, (int) byte.MaxValue, (int) byte.MaxValue);
      this.txtClientID.Cursor = Cursors.IBeam;
      this.txtClientID.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtClientID.ForeColor = Color.Blue;
      this.txtClientID.Location = new Point(139, 30);
      this.txtClientID.Margin = new Padding(4, 4, 4, 4);
      this.txtClientID.MaxLength = 8;
      this.txtClientID.Name = "txtClientID";
      this.txtClientID.ReadOnly = true;
      this.txtClientID.RightToLeft = RightToLeft.No;
      this.txtClientID.Size = new Size(117, 23);
      this.txtClientID.TabIndex = 34;
      this.txtRemark.AcceptsReturn = true;
      this.txtRemark.BackColor = Color.FromArgb(192, (int) byte.MaxValue, (int) byte.MaxValue);
      this.txtRemark.Cursor = Cursors.IBeam;
      this.txtRemark.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtRemark.ForeColor = Color.Blue;
      this.txtRemark.Location = new Point(565, 286);
      this.txtRemark.Margin = new Padding(4, 4, 4, 4);
      this.txtRemark.MaxLength = 0;
      this.txtRemark.Multiline = true;
      this.txtRemark.Name = "txtRemark";
      this.txtRemark.ReadOnly = true;
      this.txtRemark.RightToLeft = RightToLeft.No;
      this.txtRemark.Size = new Size(256, 45);
      this.txtRemark.TabIndex = 21;
      this.txtContact.AcceptsReturn = true;
      this.txtContact.BackColor = Color.FromArgb(192, (int) byte.MaxValue, (int) byte.MaxValue);
      this.txtContact.Cursor = Cursors.IBeam;
      this.txtContact.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtContact.ForeColor = Color.Blue;
      this.txtContact.Location = new Point(139, 245);
      this.txtContact.Margin = new Padding(4, 4, 4, 4);
      this.txtContact.MaxLength = 20;
      this.txtContact.Name = "txtContact";
      this.txtContact.ReadOnly = true;
      this.txtContact.RightToLeft = RightToLeft.No;
      this.txtContact.Size = new Size(203, 23);
      this.txtContact.TabIndex = 7;
      this.txtAddress.AcceptsReturn = true;
      this.txtAddress.BackColor = Color.FromArgb(192, (int) byte.MaxValue, (int) byte.MaxValue);
      this.txtAddress.Cursor = Cursors.IBeam;
      this.txtAddress.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtAddress.ForeColor = Color.Blue;
      this.txtAddress.Location = new Point(139, 286);
      this.txtAddress.Margin = new Padding(4, 4, 4, 4);
      this.txtAddress.MaxLength = 50;
      this.txtAddress.Multiline = true;
      this.txtAddress.Name = "txtAddress";
      this.txtAddress.ReadOnly = true;
      this.txtAddress.RightToLeft = RightToLeft.No;
      this.txtAddress.Size = new Size(203, 59);
      this.txtAddress.TabIndex = 8;
      this.txtNationality.AcceptsReturn = true;
      this.txtNationality.BackColor = Color.FromArgb(192, (int) byte.MaxValue, (int) byte.MaxValue);
      this.txtNationality.Cursor = Cursors.IBeam;
      this.txtNationality.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtNationality.ForeColor = Color.Blue;
      this.txtNationality.Location = new Point(565, 198);
      this.txtNationality.Margin = new Padding(4, 4, 4, 4);
      this.txtNationality.MaxLength = 20;
      this.txtNationality.Name = "txtNationality";
      this.txtNationality.ReadOnly = true;
      this.txtNationality.RightToLeft = RightToLeft.No;
      this.txtNationality.Size = new Size(203, 23);
      this.txtNationality.TabIndex = 9;
      this.txtIdentity.AcceptsReturn = true;
      this.txtIdentity.BackColor = Color.FromArgb(192, (int) byte.MaxValue, (int) byte.MaxValue);
      this.txtIdentity.Cursor = Cursors.IBeam;
      this.txtIdentity.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtIdentity.ForeColor = Color.Blue;
      this.txtIdentity.Location = new Point(139, 206);
      this.txtIdentity.Margin = new Padding(4, 4, 4, 4);
      this.txtIdentity.MaxLength = 20;
      this.txtIdentity.Name = "txtIdentity";
      this.txtIdentity.ReadOnly = true;
      this.txtIdentity.RightToLeft = RightToLeft.No;
      this.txtIdentity.Size = new Size(203, 23);
      this.txtIdentity.TabIndex = 6;
      this.txtSurName.AcceptsReturn = true;
      this.txtSurName.BackColor = Color.FromArgb(192, (int) byte.MaxValue, (int) byte.MaxValue);
      this.txtSurName.Cursor = Cursors.IBeam;
      this.txtSurName.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtSurName.ForeColor = Color.Blue;
      this.txtSurName.Location = new Point(139, 160);
      this.txtSurName.Margin = new Padding(4, 4, 4, 4);
      this.txtSurName.MaxLength = 20;
      this.txtSurName.Name = "txtSurName";
      this.txtSurName.ReadOnly = true;
      this.txtSurName.RightToLeft = RightToLeft.No;
      this.txtSurName.Size = new Size(203, 23);
      this.txtSurName.TabIndex = 5;
      this.txtFirstName.AcceptsReturn = true;
      this.txtFirstName.BackColor = Color.FromArgb(192, (int) byte.MaxValue, (int) byte.MaxValue);
      this.txtFirstName.Cursor = Cursors.IBeam;
      this.txtFirstName.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtFirstName.ForeColor = Color.Blue;
      this.txtFirstName.Location = new Point(139, 121);
      this.txtFirstName.Margin = new Padding(4, 4, 4, 4);
      this.txtFirstName.MaxLength = 20;
      this.txtFirstName.Name = "txtFirstName";
      this.txtFirstName.ReadOnly = true;
      this.txtFirstName.RightToLeft = RightToLeft.No;
      this.txtFirstName.Size = new Size(203, 23);
      this.txtFirstName.TabIndex = 4;
      this.txtCardNo.AcceptsReturn = true;
      this.txtCardNo.BackColor = Color.FromArgb(192, (int) byte.MaxValue, (int) byte.MaxValue);
      this.txtCardNo.Cursor = Cursors.IBeam;
      this.txtCardNo.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtCardNo.ForeColor = Color.Blue;
      this.txtCardNo.Location = new Point(565, 30);
      this.txtCardNo.Margin = new Padding(4, 4, 4, 4);
      this.txtCardNo.MaxLength = 0;
      this.txtCardNo.Name = "txtCardNo";
      this.txtCardNo.ReadOnly = true;
      this.txtCardNo.RightToLeft = RightToLeft.No;
      this.txtCardNo.Size = new Size(107, 23);
      this.txtCardNo.TabIndex = 2;
      this.Label3.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.Label3.Cursor = Cursors.Default;
      this.Label3.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label3.ForeColor = Color.Black;
      this.Label3.Location = new Point(32, 33);
      this.Label3.Margin = new Padding(4, 0, 4, 0);
      this.Label3.Name = "Label3";
      this.Label3.RightToLeft = RightToLeft.No;
      this.Label3.Size = new Size(76, 21);
      this.Label3.TabIndex = 35;
      this.Label3.Text = "Client ID";
      this.Label3.TextAlign = ContentAlignment.TopRight;
      this.lbInTime.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.lbInTime.Cursor = Cursors.Default;
      this.lbInTime.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.lbInTime.ForeColor = SystemColors.ControlText;
      this.lbInTime.Location = new Point(416, 160);
      this.lbInTime.Margin = new Padding(4, 0, 4, 0);
      this.lbInTime.Name = "lbInTime";
      this.lbInTime.RightToLeft = RightToLeft.No;
      this.lbInTime.Size = new Size(129, 21);
      this.lbInTime.TabIndex = 26;
      this.lbInTime.Text = "Valid StartTime";
      this.lbInTime.TextAlign = ContentAlignment.TopRight;
      this.lbOutTime.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.lbOutTime.Cursor = Cursors.Default;
      this.lbOutTime.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.lbOutTime.ForeColor = SystemColors.ControlText;
      this.lbOutTime.Location = new Point(693, 160);
      this.lbOutTime.Margin = new Padding(4, 0, 4, 0);
      this.lbOutTime.Name = "lbOutTime";
      this.lbOutTime.RightToLeft = RightToLeft.No;
      this.lbOutTime.Size = new Size(129, 21);
      this.lbOutTime.TabIndex = 25;
      this.lbOutTime.Text = "Valid End Time";
      this.lbOutTime.TextAlign = ContentAlignment.TopRight;
      this.Label27.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.Label27.Cursor = Cursors.Default;
      this.Label27.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label27.ForeColor = Color.Red;
      this.Label27.Location = new Point(437, 286);
      this.Label27.Margin = new Padding(4, 0, 4, 0);
      this.Label27.Name = "Label27";
      this.Label27.RightToLeft = RightToLeft.No;
      this.Label27.Size = new Size(119, 50);
      this.Label27.TabIndex = 22;
      this.Label27.Text = "Remark : ";
      this.Label27.TextAlign = ContentAlignment.TopRight;
      this.Label11.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.Label11.Cursor = Cursors.Default;
      this.Label11.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label11.ForeColor = SystemColors.ControlText;
      this.Label11.Location = new Point(448, 240);
      this.Label11.Margin = new Padding(4, 0, 4, 0);
      this.Label11.Name = "Label11";
      this.Label11.RightToLeft = RightToLeft.No;
      this.Label11.Size = new Size(97, 21);
      this.Label11.TabIndex = 19;
      this.Label11.Text = "Country";
      this.Label11.TextAlign = ContentAlignment.TopRight;
      this.Label10.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.Label10.Cursor = Cursors.Default;
      this.Label10.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label10.ForeColor = SystemColors.ControlText;
      this.Label10.Location = new Point(11, 249);
      this.Label10.Margin = new Padding(4, 0, 4, 0);
      this.Label10.Name = "Label10";
      this.Label10.RightToLeft = RightToLeft.No;
      this.Label10.Size = new Size(108, 21);
      this.Label10.TabIndex = 18;
      this.Label10.Text = "Contact No.";
      this.Label10.TextAlign = ContentAlignment.TopRight;
      this.Label9.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.Label9.Cursor = Cursors.Default;
      this.Label9.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label9.ForeColor = SystemColors.ControlText;
      this.Label9.Location = new Point(21, 288);
      this.Label9.Margin = new Padding(4, 0, 4, 0);
      this.Label9.Name = "Label9";
      this.Label9.RightToLeft = RightToLeft.No;
      this.Label9.Size = new Size(87, 21);
      this.Label9.TabIndex = 17;
      this.Label9.Text = "Address";
      this.Label9.TextAlign = ContentAlignment.TopRight;
      this.Label8.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.Label8.Cursor = Cursors.Default;
      this.Label8.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label8.ForeColor = SystemColors.ControlText;
      this.Label8.Location = new Point(437, 199);
      this.Label8.Margin = new Padding(4, 0, 4, 0);
      this.Label8.Name = "Label8";
      this.Label8.RightToLeft = RightToLeft.No;
      this.Label8.Size = new Size(108, 21);
      this.Label8.TabIndex = 16;
      this.Label8.Text = "Nationality";
      this.Label8.TextAlign = ContentAlignment.TopRight;
      this._Label7_0.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this._Label7_0.Cursor = Cursors.Default;
      this._Label7_0.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this._Label7_0.ForeColor = SystemColors.ControlText;
      this._Label7_0.Location = new Point(11, 209);
      this._Label7_0.Margin = new Padding(4, 0, 4, 0);
      this._Label7_0.Name = "_Label7_0";
      this._Label7_0.RightToLeft = RightToLeft.No;
      this._Label7_0.Size = new Size(108, 21);
      this._Label7_0.TabIndex = 15;
      this._Label7_0.Text = "Passport No.";
      this._Label7_0.TextAlign = ContentAlignment.TopRight;
      this.Label6.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.Label6.Cursor = Cursors.Default;
      this.Label6.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label6.ForeColor = SystemColors.ControlText;
      this.Label6.Location = new Point(64, 81);
      this.Label6.Margin = new Padding(4, 0, 4, 0);
      this.Label6.Name = "Label6";
      this.Label6.RightToLeft = RightToLeft.No;
      this.Label6.Size = new Size(44, 21);
      this.Label6.TabIndex = 14;
      this.Label6.Text = "Sex";
      this.Label6.TextAlign = ContentAlignment.TopRight;
      this.lbValidEnd.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.lbValidEnd.Cursor = Cursors.Default;
      this.lbValidEnd.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.lbValidEnd.ForeColor = SystemColors.ControlText;
      this.lbValidEnd.Location = new Point(693, 124);
      this.lbValidEnd.Margin = new Padding(4, 0, 4, 0);
      this.lbValidEnd.Name = "lbValidEnd";
      this.lbValidEnd.RightToLeft = RightToLeft.No;
      this.lbValidEnd.Size = new Size(129, 21);
      this.lbValidEnd.TabIndex = 13;
      this.lbValidEnd.Text = "Valid End Date";
      this.lbValidEnd.TextAlign = ContentAlignment.TopRight;
      this.Label24.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.Label24.Cursor = Cursors.Default;
      this.Label24.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label24.ForeColor = SystemColors.ControlText;
      this.Label24.Location = new Point(416, 124);
      this.Label24.Margin = new Padding(4, 0, 4, 0);
      this.Label24.Name = "Label24";
      this.Label24.RightToLeft = RightToLeft.No;
      this.Label24.Size = new Size(129, 21);
      this.Label24.TabIndex = 12;
      this.Label24.Text = "Valid Start Date";
      this.Label24.TextAlign = ContentAlignment.TopRight;
      this.Label4.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.Label4.Cursor = Cursors.Default;
      this.Label4.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label4.ForeColor = SystemColors.ControlText;
      this.Label4.Location = new Point(11, (int) sbyte.MaxValue);
      this.Label4.Margin = new Padding(4, 0, 4, 0);
      this.Label4.Name = "Label4";
      this.Label4.RightToLeft = RightToLeft.No;
      this.Label4.Size = new Size(97, 21);
      this.Label4.TabIndex = 11;
      this.Label4.Text = "First Name";
      this.Label4.TextAlign = ContentAlignment.TopRight;
      this.Label5.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.Label5.Cursor = Cursors.Default;
      this.Label5.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label5.ForeColor = SystemColors.ControlText;
      this.Label5.Location = new Point(21, 166);
      this.Label5.Margin = new Padding(4, 0, 4, 0);
      this.Label5.Name = "Label5";
      this.Label5.RightToLeft = RightToLeft.No;
      this.Label5.Size = new Size(87, 21);
      this.Label5.TabIndex = 10;
      this.Label5.Text = "Surname";
      this.Label5.TextAlign = ContentAlignment.TopRight;
      this.Label28.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 192);
      this.Label28.Cursor = Cursors.Default;
      this.Label28.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label28.ForeColor = SystemColors.ControlText;
      this.Label28.Location = new Point(448, 30);
      this.Label28.Margin = new Padding(4, 0, 4, 0);
      this.Label28.Name = "Label28";
      this.Label28.RightToLeft = RightToLeft.No;
      this.Label28.Size = new Size(97, 21);
      this.Label28.TabIndex = 3;
      this.Label28.Text = "Card No.";
      this.Label28.TextAlign = ContentAlignment.TopRight;
      this.lbBuilding.BackColor = Color.FromArgb(192, (int) byte.MaxValue, 192);
      this.lbBuilding.Cursor = Cursors.Default;
      this.lbBuilding.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.lbBuilding.ForeColor = SystemColors.ControlText;
      this.lbBuilding.Location = new Point(363, 31);
      this.lbBuilding.Margin = new Padding(4, 0, 4, 0);
      this.lbBuilding.Name = "lbBuilding";
      this.lbBuilding.RightToLeft = RightToLeft.No;
      this.lbBuilding.Size = new Size(97, 21);
      this.lbBuilding.TabIndex = 24;
      this.lbBuilding.Text = "Building No.";
      this.lbBuilding.TextAlign = ContentAlignment.TopRight;
      this.lblMessage1.BackColor = Color.White;
      this.lblMessage1.Cursor = Cursors.Default;
      this.lblMessage1.Font = new Font("Arial", 14.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.lblMessage1.ForeColor = Color.Blue;
      this.lblMessage1.Location = new Point(656, 26);
      this.lblMessage1.Margin = new Padding(4, 0, 4, 0);
      this.lblMessage1.Name = "lblMessage1";
      this.lblMessage1.RightToLeft = RightToLeft.No;
      this.lblMessage1.Size = new Size(385, 50);
      this.lblMessage1.TabIndex = 54;
      this.lblMessage1.TextAlign = ContentAlignment.TopCenter;
      this.lblMessage1.Visible = false;
      this.Label1.BackColor = Color.Transparent;
      this.Label1.Cursor = Cursors.Default;
      this.Label1.Font = new Font("Arial", 24f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.Label1.ForeColor = Color.Blue;
      this.Label1.Location = new Point(16, 6);
      this.Label1.Margin = new Padding(4, 0, 4, 0);
      this.Label1.Name = "Label1";
      this.Label1.RightToLeft = RightToLeft.No;
      this.Label1.Size = new Size(983, 41);
      this.Label1.TabIndex = 52;
      this.Label1.Text = "Admin Mode";
      this.Label1.TextAlign = ContentAlignment.TopCenter;
      this.lblMessage.BackColor = Color.White;
      this.lblMessage.Cursor = Cursors.Default;
      this.lblMessage.Font = new Font("Arial", 13.5f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.lblMessage.ForeColor = Color.Red;
      this.lblMessage.Location = new Point(16, 174);
      this.lblMessage.Margin = new Padding(4, 0, 4, 0);
      this.lblMessage.Name = "lblMessage";
      this.lblMessage.RightToLeft = RightToLeft.No;
      this.lblMessage.Size = new Size(983, 41);
      this.lblMessage.TabIndex = 50;
      this.lblMessage.TextAlign = ContentAlignment.TopCenter;
      this.Label14.BackColor = Color.FromArgb(192, (int) byte.MaxValue, 192);
      this.Label14.Cursor = Cursors.Default;
      this.Label14.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label14.ForeColor = Color.Blue;
      this.Label14.Location = new Point(21, 30);
      this.Label14.Margin = new Padding(4, 0, 4, 0);
      this.Label14.Name = "Label14";
      this.Label14.RightToLeft = RightToLeft.No;
      this.Label14.Size = new Size(108, 21);
      this.Label14.TabIndex = 36;
      this.Label14.Text = "Card Type ";
      this.Label14.TextAlign = ContentAlignment.TopRight;
      this.lbReadCardHeader.BackColor = Color.Transparent;
      this.lbReadCardHeader.Cursor = Cursors.Default;
      this.lbReadCardHeader.Font = new Font("Arial", 18f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.lbReadCardHeader.ForeColor = Color.Red;
      this.lbReadCardHeader.Location = new Point(16, 55);
      this.lbReadCardHeader.Margin = new Padding(4, 0, 4, 0);
      this.lbReadCardHeader.Name = "lbReadCardHeader";
      this.lbReadCardHeader.RightToLeft = RightToLeft.No;
      this.lbReadCardHeader.Size = new Size(983, 31);
      this.lbReadCardHeader.TabIndex = 48;
      this.lbReadCardHeader.Text = "CANCEL  CARD";
      this.lbReadCardHeader.TextAlign = ContentAlignment.TopCenter;
      this.lbFloor.BackColor = Color.FromArgb(192, (int) byte.MaxValue, 192);
      this.lbFloor.Cursor = Cursors.Default;
      this.lbFloor.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.lbFloor.ForeColor = SystemColors.ControlText;
      this.lbFloor.Location = new Point(11, 20);
      this.lbFloor.Margin = new Padding(4, 0, 4, 0);
      this.lbFloor.Name = "lbFloor";
      this.lbFloor.RightToLeft = RightToLeft.No;
      this.lbFloor.Size = new Size(76, 21);
      this.lbFloor.TabIndex = 28;
      this.lbFloor.Text = "Level No.";
      this.lbFloor.TextAlign = ContentAlignment.TopRight;
      this.Frame2.BackColor = Color.FromArgb((int) byte.MaxValue, (int) byte.MaxValue, 128);
      this.Frame2.Controls.Add((Control) this.cmdCancel);
      this.Frame2.Controls.Add((Control) this.cmdReturn);
      this.Frame2.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.Frame2.ForeColor = SystemColors.ControlText;
      this.Frame2.Location = new Point(16, 577);
      this.Frame2.Margin = new Padding(4, 4, 4, 4);
      this.Frame2.Name = "Frame2";
      this.Frame2.Padding = new Padding(0);
      this.Frame2.RightToLeft = RightToLeft.No;
      this.Frame2.Size = new Size(983, 80);
      this.Frame2.TabIndex = 53;
      this.Frame2.TabStop = false;
      this.Timer1.Enabled = true;
      this.Timer1.Interval = 500;
      this.Frame1.BackColor = Color.FromArgb(192, (int) byte.MaxValue, 192);
      this.Frame1.Controls.Add((Control) this.ZoneFrame);
      this.Frame1.Controls.Add((Control) this.txtBuilding);
      this.Frame1.Controls.Add((Control) this.txtCardType);
      this.Frame1.Controls.Add((Control) this.RoomFrame);
      this.Frame1.Controls.Add((Control) this.FloorFrame);
      this.Frame1.Controls.Add((Control) this.Label14);
      this.Frame1.Controls.Add((Control) this.lbBuilding);
      this.Frame1.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Frame1.ForeColor = SystemColors.ControlText;
      this.Frame1.Location = new Point(16, 95);
      this.Frame1.Margin = new Padding(4, 4, 4, 4);
      this.Frame1.Name = "Frame1";
      this.Frame1.Padding = new Padding(0);
      this.Frame1.RightToLeft = RightToLeft.No;
      this.Frame1.Size = new Size(983, 70);
      this.Frame1.TabIndex = 51;
      this.Frame1.TabStop = false;
      this.Frame1.Text = "READ DATA :";
      this.ZoneFrame.BackColor = Color.FromArgb(192, (int) byte.MaxValue, 192);
      this.ZoneFrame.Controls.Add((Control) this.txtZoneNo);
      this.ZoneFrame.Controls.Add((Control) this.lbZoneNo);
      this.ZoneFrame.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.ZoneFrame.ForeColor = SystemColors.ControlText;
      this.ZoneFrame.Location = new Point(565, 10);
      this.ZoneFrame.Margin = new Padding(4, 4, 4, 4);
      this.ZoneFrame.Name = "ZoneFrame";
      this.ZoneFrame.Padding = new Padding(0);
      this.ZoneFrame.RightToLeft = RightToLeft.No;
      this.ZoneFrame.Size = new Size(183, 50);
      this.ZoneFrame.TabIndex = 49;
      this.ZoneFrame.TabStop = false;
      this.txtZoneNo.AcceptsReturn = true;
      this.txtZoneNo.BackColor = SystemColors.Window;
      this.txtZoneNo.Cursor = Cursors.IBeam;
      this.txtZoneNo.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtZoneNo.ForeColor = SystemColors.WindowText;
      this.txtZoneNo.Location = new Point(117, 20);
      this.txtZoneNo.Margin = new Padding(4, 4, 4, 4);
      this.txtZoneNo.MaxLength = 0;
      this.txtZoneNo.Name = "txtZoneNo";
      this.txtZoneNo.ReadOnly = true;
      this.txtZoneNo.RightToLeft = RightToLeft.No;
      this.txtZoneNo.Size = new Size(43, 23);
      this.txtZoneNo.TabIndex = 50;
      this.lbZoneNo.BackColor = Color.FromArgb(192, (int) byte.MaxValue, 192);
      this.lbZoneNo.Cursor = Cursors.Default;
      this.lbZoneNo.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.lbZoneNo.ForeColor = SystemColors.ControlText;
      this.lbZoneNo.Location = new Point(21, 20);
      this.lbZoneNo.Margin = new Padding(4, 0, 4, 0);
      this.lbZoneNo.Name = "lbZoneNo";
      this.lbZoneNo.RightToLeft = RightToLeft.No;
      this.lbZoneNo.Size = new Size(76, 21);
      this.lbZoneNo.TabIndex = 51;
      this.lbZoneNo.Text = "Zone No. ";
      this.lbZoneNo.TextAlign = ContentAlignment.TopRight;
      this.txtBuilding.AcceptsReturn = true;
      this.txtBuilding.BackColor = Color.FromArgb(192, (int) byte.MaxValue, (int) byte.MaxValue);
      this.txtBuilding.Cursor = Cursors.IBeam;
      this.txtBuilding.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtBuilding.ForeColor = Color.Blue;
      this.txtBuilding.Location = new Point(480, 30);
      this.txtBuilding.Margin = new Padding(4, 4, 4, 4);
      this.txtBuilding.MaxLength = 0;
      this.txtBuilding.Name = "txtBuilding";
      this.txtBuilding.ReadOnly = true;
      this.txtBuilding.RightToLeft = RightToLeft.No;
      this.txtBuilding.Size = new Size(53, 23);
      this.txtBuilding.TabIndex = 38;
      this.RoomFrame.BackColor = Color.FromArgb(192, (int) byte.MaxValue, 192);
      this.RoomFrame.Controls.Add((Control) this.txtRoomNo);
      this.RoomFrame.Controls.Add((Control) this.Label2);
      this.RoomFrame.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.RoomFrame.ForeColor = SystemColors.ControlText;
      this.RoomFrame.Location = new Point(779, 10);
      this.RoomFrame.Margin = new Padding(4, 4, 4, 4);
      this.RoomFrame.Name = "RoomFrame";
      this.RoomFrame.Padding = new Padding(0);
      this.RoomFrame.RightToLeft = RightToLeft.No;
      this.RoomFrame.Size = new Size(183, 50);
      this.RoomFrame.TabIndex = 30;
      this.RoomFrame.TabStop = false;
      this.txtRoomNo.AcceptsReturn = true;
      this.txtRoomNo.BackColor = Color.FromArgb(192, (int) byte.MaxValue, (int) byte.MaxValue);
      this.txtRoomNo.Cursor = Cursors.IBeam;
      this.txtRoomNo.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtRoomNo.ForeColor = Color.Blue;
      this.txtRoomNo.Location = new Point(85, 20);
      this.txtRoomNo.Margin = new Padding(4, 4, 4, 4);
      this.txtRoomNo.MaxLength = 0;
      this.txtRoomNo.Name = "txtRoomNo";
      this.txtRoomNo.RightToLeft = RightToLeft.No;
      this.txtRoomNo.Size = new Size(85, 23);
      this.txtRoomNo.TabIndex = 40;
      this.Label2.BackColor = Color.FromArgb(192, (int) byte.MaxValue, 192);
      this.Label2.Cursor = Cursors.Default;
      this.Label2.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.Label2.ForeColor = SystemColors.ControlText;
      this.Label2.Location = new Point(11, 21);
      this.Label2.Margin = new Padding(4, 0, 4, 0);
      this.Label2.Name = "Label2";
      this.Label2.RightToLeft = RightToLeft.No;
      this.Label2.Size = new Size(55, 21);
      this.Label2.TabIndex = 31;
      this.Label2.Text = "Room";
      this.Label2.TextAlign = ContentAlignment.TopRight;
      this.FloorFrame.BackColor = Color.FromArgb(192, (int) byte.MaxValue, 192);
      this.FloorFrame.Controls.Add((Control) this.txtFloorNo);
      this.FloorFrame.Controls.Add((Control) this.lbFloor);
      this.FloorFrame.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.FloorFrame.ForeColor = SystemColors.ControlText;
      this.FloorFrame.Location = new Point(576, 10);
      this.FloorFrame.Margin = new Padding(4, 4, 4, 4);
      this.FloorFrame.Name = "FloorFrame";
      this.FloorFrame.Padding = new Padding(0);
      this.FloorFrame.RightToLeft = RightToLeft.No;
      this.FloorFrame.Size = new Size(172, 50);
      this.FloorFrame.TabIndex = 27;
      this.FloorFrame.TabStop = false;
      this.txtFloorNo.AcceptsReturn = true;
      this.txtFloorNo.BackColor = Color.FromArgb(192, (int) byte.MaxValue, (int) byte.MaxValue);
      this.txtFloorNo.Cursor = Cursors.IBeam;
      this.txtFloorNo.Font = new Font("Arial", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.txtFloorNo.ForeColor = Color.Blue;
      this.txtFloorNo.Location = new Point(107, 20);
      this.txtFloorNo.Margin = new Padding(4, 4, 4, 4);
      this.txtFloorNo.MaxLength = 0;
      this.txtFloorNo.Name = "txtFloorNo";
      this.txtFloorNo.ReadOnly = true;
      this.txtFloorNo.RightToLeft = RightToLeft.No;
      this.txtFloorNo.Size = new Size(53, 23);
      this.txtFloorNo.TabIndex = 39;
      this.AutoScaleDimensions = new SizeF(8f, 16f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(1045, 686);
      this.Controls.Add((Control) this.IssueCardFrame);
      this.Controls.Add((Control) this.lblMessage1);
      this.Controls.Add((Control) this.Label1);
      this.Controls.Add((Control) this.lblMessage);
      this.Controls.Add((Control) this.lbReadCardHeader);
      this.Controls.Add((Control) this.Frame2);
      this.Controls.Add((Control) this.Frame1);
      this.Margin = new Padding(4, 4, 4, 4);
      this.Name = "Form_CancelCardDMS";
      this.StartPosition = FormStartPosition.CenterScreen;
      this.Text = "ACCOMMODATION MANAGEMENT SYSTEM";
      this.FormClosing += new FormClosingEventHandler(this.Form_CancelCardDMS_FormClosing);
      this.IssueCardFrame.ResumeLayout(false);
      this.IssueCardFrame.PerformLayout();
      this.Frame2.ResumeLayout(false);
      this.Frame1.ResumeLayout(false);
      this.Frame1.PerformLayout();
      this.ZoneFrame.ResumeLayout(false);
      this.ZoneFrame.PerformLayout();
      this.RoomFrame.ResumeLayout(false);
      this.RoomFrame.PerformLayout();
      this.FloorFrame.ResumeLayout(false);
      this.FloorFrame.PerformLayout();
      this.ResumeLayout(false);
    }

    public Form_CancelCardDMS() => this.InitializeComponent();

    private void cmdReturn_Click(object sender, EventArgs e)
    {
      this.Visible = false;
      ModDoorLockSystem.Form_AdminDMS_Ptr.Visible = true;
    }

    private void Form_CancelCardDMS_FormClosing(object sender, FormClosingEventArgs e)
    {
      Application.Exit();
    }
  }
}
